name: Nightly PKG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: write  # We need this to be able to cancel workflow if job fails

jobs:
  Windows:
    if: github.repository == 'darktable-org/darktable' || github.event_name == 'workflow_dispatch'
    name: Nightly darktable Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        btype:
          - Release
        msystem:
          - UCRT64
          - CLANGARM64
        target:
          - skiptest
        generator:
          - Ninja
        eco: [-DBINARY_PACKAGE_BUILD=ON]
        include:
          - msystem: UCRT64
            os: windows-latest
          - msystem: CLANGARM64
            os: windows-11-arm
    defaults:
      run:
        shell: msys2 {0}
    env:
      SRC_DIR: ${{ github.workspace }}/src
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_PREFIX: ${{ github.workspace }}/install
      ECO: ${{ matrix.eco }}
      CMAKE_BUILD_TYPE: ${{ matrix.btype }}
      TARGET: ${{ matrix.target }}
      GENERATOR: ${{ matrix.generator }}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            git
            intltool
            po4a
          pacboy: >-
            cc:p
            cmake:p
            libxslt:p
            ninja:p
            python-jsonschema:p
            curl:p
            drmingw:p
            gcc-libs:p
            gettext:p
            gmic:p
            graphicsmagick:p
            gtk3:p
            icu:p
            imath:p
            iso-codes:p
            lcms2:p
            lensfun:p
            libavif:p
            libgphoto2:p
            libheif:p
            libjpeg-turbo:p
            libjxl:p
            libpng:p
            librsvg:p
            libsecret:p
            libtiff:p
            libwebp:p
            libxml2:p
            lua54:p
            omp:p
            opencv:p
            openexr:p
            openjpeg2:p
            osm-gps-map:p
            portmidi:p
            potrace:p
            pugixml:p
            SDL2:p
            sqlite3:p
            webp-pixbuf-loader:p
            zlib:p
          update: true
      - name: Install the latest not yet broken version of cairo
        run: |
          # It's a temporary fix, to be removed when the issue with cairo will be resolved
          REPO="$(echo "${MSYSTEM:-UCRT64}" | tr '[:upper:]' '[:lower:]')"
          if [ "$MSYSTEM" == "UCRT64" ]; then
            PREFIX="mingw-w64-ucrt-x86_64"
          else
            PREFIX="mingw-w64-clang-aarch64"
          fi
          pacman -U --noconfirm https://repo.msys2.org/mingw/${REPO}/${PREFIX}-cairo-1.18.4-4-any.pkg.tar.zst
      - name: Build and install the latest compatible version of exiv2
        run: |
          git clone --branch v0.27.7 --depth 1 https://github.com/Exiv2/exiv2 src-exiv2
          cd src-exiv2
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DEXIV2_ENABLE_BMFF=ON \
            -DEXIV2_ENABLE_NLS=ON \
            -DEXIV2_ENABLE_VIDEO=OFF \
            -DEXIV2_ENABLE_WIN_UNICODE=ON \
            -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX}
          cmake --build build
          cmake --install build
          cd ..
      - name: Cancel workflow if job fails
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.5
      - run: git config --global core.autocrlf input
        shell: bash
      - name: Checkout darktable master branch
        run: |
          # Note that we can't make a shallow clone to reduce clone traffic and time, as we have to
          # fetch the entire history to correctly generate the version for the installation package filename
          git clone -b ${{ github.ref_name }} https://github.com/${{ github.repository }} src
          pushd src
          git submodule init
          git config submodule.src/tests/integration.update none
          git submodule update
          popd
      - name: Update Lensfun data
        run: |
          lensfun-update-data
      - name: Build and Install
        run: |
          cmake -E make_directory "${BUILD_DIR}"
          cmake -E make_directory "${INSTALL_PREFIX}"
          $(cygpath ${SRC_DIR})/.ci/ci-script.sh
